/* SPDX-License-Identifier: CC0-1.0 */

#include "initfini/initfini.h"
#include <stdlib.h>

/* This function is generated by the linker to call constructors. */
extern void __wasm_call_ctors(void);

/* If the application has a zero-argument main, it will be renamed to this
 * function. Otherwise, our own function that prepares argv and argc will be
 * linked as this. */
extern int __original_main(void);

void _start(void)
{
    __wasm_call_ctors();

    int ret = __original_main();

    __libc_run_atexit_handlers();

    if (ret != 0) {
        _Exit(ret);
    }
}
