/* SPDX-License-Identifier: CC0-1.0 */

#include "basic/wasi/api.h"
#include "initfini/initfini.h"
#include <stdlib.h>
#include <sysexits.h>

extern char **environ;

/* This function is generated by the linker to call constructors. */
extern void __wasm_call_ctors(void);

/* If the application has a zero-argument main, it will be renamed to this
 * function. Otherwise, our own function that prepares argv and argc will be
 * linked as this. */
extern int __original_main(void);

static void do_init(void)
{
    __wasi_errno_t err;

    /* Get the sizes of the arrays we'll have to create to copy in the args. */
    size_t environ_count;
    size_t environ_buf_size;
    err = __wasi_environ_sizes_get(&environ_count, &environ_buf_size);
    if (err != __WASI_ERRNO_SUCCESS) {
        _Exit(EX_OSERR);
    }

    /* Add 1 for the NULL pointer to mark the end, and check for overflow. */
    size_t num_ptrs = environ_count + 1;
    if (num_ptrs == 0) {
        _Exit(EX_SOFTWARE);
    }

    /* Allocate memory for storing the environment block. */
    char *environ_buf = malloc(environ_buf_size);
    if (!environ_buf) {
        _Exit(EX_SOFTWARE);
    }

    /* Allocate memory for the array of pointers. */
    environ = calloc(num_ptrs, sizeof(char *));
    if (!environ) {
        free(environ_buf);
        _Exit(EX_SOFTWARE);
    }

    /* Fill the environment block and environ. */
    err = __wasi_environ_get((uint8_t **)environ, (uint8_t *)environ_buf);
    if (err != __WASI_ERRNO_SUCCESS) {
        free(environ_buf);
        free(environ);
        _Exit(EX_OSERR);
    }

    __wasm_call_ctors();
}

void _start(void)
{
    do_init();
    exit(__original_main());
}
